### ISSUE TITLE
[BUG] bin/magento setup:di:compile issue

### ISSUE THREAD

**Issue by LuukS-stimmt** [postnl/postnl-magento2#392] opened 2024-08-09 11:40 UTC
**To Reproduce**
run `bin/magento setup:di:compile`

**Fix / Workaround**
Please remove the comma in: 
https://github.com/postnl/postnl-magento2/blob/1e8f126ea3e3062cfbbc592c43fd1eb640592c8b/Controller/Adminhtml/Order/MassChangeMulticolli.php#L31 
And in:
https://github.com/postnl/postnl-magento2/blob/1e8f126ea3e3062cfbbc592c43fd1eb640592c8b/Controller/Adminhtml/Shipment/GetSmartReturnLabel.php#L31
And:
https://github.com/postnl/postnl-magento2/blob/1e8f126ea3e3062cfbbc592c43fd1eb640592c8b/Service/Shipment/ShipmentLoader.php#L31

**Unexpected result**
`Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 126.0 MiBsyntax error, unexpected ')', expecting variable (T_VARIABLE)#0 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('TIG\\PostNL\\Cont...')
#2 [internal function]: spl_autoload_call('TIG\\PostNL\\Cont...')
#3 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('TIG\\PostNL\\Cont...')
#4 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('TIG\\PostNL\\Cont...', '/var/www/html/v...')
#5 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#6 /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/var/www/html/v...')
#7 /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /var/www/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#9 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
`

Magento version: 2.4.3
PHP version: 7.4
TIG PostNL version: 1.15.2

**Comment by YachYaroslav** [comment] 2024-08-09 15:28
Hi @LuukS-stimmt, this is a duplicate of https://github.com/postnl/postnl-magento2/issues/386. PostNL developers are acknowledged about this problem when using PHP 7.4.

**Closed** 2024-08-27 08:20 UTC
