### ISSUE TITLE
[QUESTION] Swagger documentation incomplete

### ISSUE THREAD

**Issue by memen45** [postnl/postnl-magento2#327] opened 2022-09-06 08:40 UTC
The `shop.domain.com/swagger` endpoint shows all documentation for the REST API. Adding an admin token as api_key in the top right will show the full list of available endpoints for the admin. Trying `PUT /V1/postnl/shipments`, there are no parameters required, nor any body. However, on try out, I receive the following response:
```
{
  "message": "Een ID is nodig. Stel het ID in en probeer het opnieuw."
}
```
I have searched this whole repository, but I cannot find this text or follow where the ShipmentRepository::create fails. Is the documentation incomplete? 

![screen](https://user-images.githubusercontent.com/27782135/188588867-7f909ac8-60e8-4300-8201-3512c0de7f83.png)

**Comment by tig-jeffreybranderhorst** [comment] 2022-09-06 14:10
Hi @memen45 ,

It seems like this is not totally working as intended, I will place this on our backlog to fix. We will release this as soon as possible. If needed we can give you a patch when we have created a fix for this issue.

Have a great day,
Jeffrey

**Comment by memen45** [comment] 2022-09-06 14:33
Thanks for your reply! Looking forward to the fix, waiting is not a problem. It would be great though if you could point me to some documentation with regards to the postnl webapi in the meantime. Is there any or does it rely on 'code as documentation' :p

**Comment by tig-jeffreybranderhorst** [comment] 2022-09-07 07:16
Hi @memen45 ,

At this moment, we don't have documentation for the API of the extension.  If you mean API documentation of PostNL itself this does excist https://developer.postnl.nl/browse-apis/send-and-track/shipping-webservice/documentation/ 

Have a great day,
Jeffrey

**Closed** 2024-02-06 11:54 UTC
Labels: question
